// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGa1FMSywtCuMxQmtDZrM_pjE6OHqlLnI',
    appId: '1:88697282371:web:5f94e9c800e8c40e6659f6',
    messagingSenderId: '88697282371',
    projectId: 'hit-the-deck-manager',
    authDomain: 'hit-the-deck-manager.firebaseapp.com',
    storageBucket: 'hit-the-deck-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1yldHBVyOicu3nFZm-LkXN7Hui_rUJu4',
    appId: '1:88697282371:android:dd6875401b0cf1786659f6',
    messagingSenderId: '88697282371',
    projectId: 'hit-the-deck-manager',
    storageBucket: 'hit-the-deck-manager.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPUCUlMM_UBHs3T13E4csRItHQopQ86iM',
    appId: '1:88697282371:ios:2fda9f7b18f5974d6659f6',
    messagingSenderId: '88697282371',
    projectId: 'hit-the-deck-manager',
    storageBucket: 'hit-the-deck-manager.firebasestorage.app',
    iosBundleId: 'com.hitthedecksports.manager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPUCUlMM_UBHs3T13E4csRItHQopQ86iM',
    appId: '1:88697282371:ios:5d8bbfca4c5a157d6659f6',
    messagingSenderId: '88697282371',
    projectId: 'hit-the-deck-manager',
    storageBucket: 'hit-the-deck-manager.firebasestorage.app',
    iosBundleId: 'com.example.hitTheDeckManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGa1FMSywtCuMxQmtDZrM_pjE6OHqlLnI',
    appId: '1:88697282371:web:81336d6deeaa6f296659f6',
    messagingSenderId: '88697282371',
    projectId: 'hit-the-deck-manager',
    authDomain: 'hit-the-deck-manager.firebaseapp.com',
    storageBucket: 'hit-the-deck-manager.firebasestorage.app',
  );
}
