import '../../features/inventory/domain/models/inventory_enums.dart';
import '../../features/inventory/domain/models/inventory_item.dart';
import '../../features/transactions/domain/models/sale_transaction.dart';
import '../../features/transactions/domain/models/transaction_enums.dart';

abstract final class DevelopmentSampleData {
  static List<InventoryItem> createInventoryItems() {
    return [
      InventoryItem(
        id: 'sample-item-available-bat',
        inventoryNumber: 'BAT-2608-0001',
        category: InventoryCategory.bat,
        brand: 'Combat',
        model: 'Spec H1',
        acquisitionType: AcquisitionType.purchased,
        acquisitionValueCents: 20000,
        condition: InventoryCondition.likeNew,
        status: InventoryStatus.available,
        purchaseDate: DateTime(2026, 8, 1),
        newValueCents: 49999,
        askingPriceCents: 32500,
        minimumPriceCents: 27500,
        notes: 'Development sample: available BBCOR bat.',
        lengthInches: 32,
        weightOunces: 29,
        drop: -3,
        certification: 'BBCOR',
      ),
      InventoryItem(
        id: 'sample-item-available-glove',
        inventoryNumber: 'GLV-2608-0001',
        category: InventoryCategory.glove,
        brand: 'Wilson',
        model: 'A2000',
        acquisitionType: AcquisitionType.traded,
        acquisitionValueCents: 14000,
        condition: InventoryCondition.good,
        status: InventoryStatus.available,
        purchaseDate: DateTime(2026, 8, 2),
        newValueCents: 29999,
        askingPriceCents: 22500,
        minimumPriceCents: 19000,
        notes: 'Development sample: available infield glove.',
        gloveSizeInches: 11.5,
        handOrientation: 'Right Hand Throw',
      ),
      InventoryItem(
        id: 'sample-item-inactive-helmet',
        inventoryNumber: 'HLM-2608-0001',
        category: InventoryCategory.helmet,
        brand: 'Rawlings',
        model: 'Mach',
        acquisitionType: AcquisitionType.purchased,
        acquisitionValueCents: 5000,
        condition: InventoryCondition.good,
        status: InventoryStatus.inactive,
        purchaseDate: DateTime(2026, 7, 25),
        newValueCents: 7999,
        askingPriceCents: 6500,
        notes: 'Development sample: inactive helmet.',
      ),
      InventoryItem(
        id: 'sample-item-broken-bat',
        inventoryNumber: 'BAT-2607-0001',
        category: InventoryCategory.bat,
        brand: 'Easton',
        model: 'Hype Fire',
        acquisitionType: AcquisitionType.purchased,
        acquisitionValueCents: 17500,
        condition: InventoryCondition.fair,
        status: InventoryStatus.broken,
        purchaseDate: DateTime(2026, 7, 20),
        newValueCents: 34999,
        askingPriceCents: 22500,
        notes: 'Development sample: broken bat requiring review.',
        lengthInches: 31,
        weightOunces: 26,
        drop: -5,
        certification: 'USSSA',
      ),
      InventoryItem(
        id: 'sample-item-sold-bat',
        inventoryNumber: 'BAT-2607-0002',
        category: InventoryCategory.bat,
        brand: 'Louisville Slugger',
        model: 'Meta',
        acquisitionType: AcquisitionType.purchased,
        acquisitionValueCents: 21000,
        condition: InventoryCondition.likeNew,
        status: InventoryStatus.sold,
        purchaseDate: DateTime(2026, 7, 15),
        newValueCents: 49999,
        askingPriceCents: 34000,
        minimumPriceCents: 30000,
        notes: 'Development sample: sold BBCOR bat.',
        lengthInches: 33,
        weightOunces: 30,
        drop: -3,
        certification: 'BBCOR',
      ),
      InventoryItem(
        id: 'sample-item-sold-catchers-gear',
        inventoryNumber: 'CTG-2607-0001',
        category: InventoryCategory.catchersGear,
        brand: 'All-Star',
        model: 'System7 Axis',
        acquisitionType: AcquisitionType.consignment,
        acquisitionValueCents: 15000,
        condition: InventoryCondition.good,
        status: InventoryStatus.sold,
        purchaseDate: DateTime(2026, 7, 10),
        newValueCents: 39999,
        askingPriceCents: 26000,
        minimumPriceCents: 22500,
        notes: 'Development sample: sold catcher’s gear set.',
        catchersGearSize: 'Intermediate',
      ),
    ];
  }

  static List<SaleTransaction> createSales() {
    return [
      SaleTransaction(
        id: 'sample-sale-bat',
        inventoryItemId: 'sample-item-sold-bat',
        salePriceCents: 32500,
        saleDate: DateTime(2026, 8, 3),
        paymentMethod: PaymentMethod.venmo,
        notes: 'Development sample sale completed at a tournament.',
        acquisitionValueCents: 21000,
      ),
      SaleTransaction(
        id: 'sample-sale-catchers-gear',
        inventoryItemId: 'sample-item-sold-catchers-gear',
        salePriceCents: 25000,
        saleDate: DateTime(2026, 8, 2),
        paymentMethod: PaymentMethod.cash,
        notes: 'Development sample sale for catcher’s gear.',
        acquisitionValueCents: 15000,
      ),
    ];
  }
}
